### ISSUE TITLE
Why just runtime?

### ISSUE THREAD

**Issue by No3371** [gydisme/Unity-Game-Framwork#1]
By selecting "Editor And Runtime", editor time method call is possible.

**Comment by gydisme** [comment]
could you explain a case that called in editor time?

if it's possible, I could add an option to unlock it.

**Comment by No3371** [comment]
![default](https://user-images.githubusercontent.com/1814971/31596553-cc3243de-b275-11e7-96e8-47db38f402e2.png)

Editor time tools.

**Comment by No3371** [comment]
https://github.com/No3371/MethodCaller_Unity

**Comment by gydisme** [comment]
Updated for the request.

by the way, I know unityevent supports run in editor mode, 
what I limited is for preventing unexpected run.

anyway, it gets free now.
