### ISSUE TITLE
NGUI dependancy in RenderQueueModifier

### ISSUE THREAD

**Issue by rfadeev** [gydisme/Unity-Game-Framwork#3]
Hello,

`RenderQueueModifier` class has reference to [UIWidget](https://github.com/gydisme/Unity-Game-Framwork/blob/4e36bf53b94562a5ce13fe0d8209cbd08f1c4e2a/RenderQueueModifier.cs#L12). This results in compilation error if NGUI is not in the Unity project and Unity-Game-Framwork is used as git submodule inside Assets folder (like "Assets/Unity-Game-Framwork"). Maybe add this requirement to repository readme for people who would like to use this as a submodule?

Regards,
Roman

**Comment by gydisme** [comment]
Moved the RenderQueueModifier to /Assets/RenderQueueModifier/
and also added a Readme file

thanks

**Comment by rfadeev** [comment]
@gydisme Thanks! Maybe add NGUI requirement to main repository readme? Since after moving the file while Unity project is dependant on NGUI, not just repository as submodule.

Also, have you considered removing `RenderQueueModifier` to get rid of NGUI dependancy? Of course anybody can fork original repository and remove `RenderQueueModifier` themselves, but I'm just wondering since it's the only class dependant on NGUI.

**Comment by gydisme** [comment]
The project is more like a module set, instead an unity-project.
since I used UGUI on my work now,  I will remove the RenderQueueModifier one day in the future.

Thanks for your feedback.

**Comment by rfadeev** [comment]
Got it, thank you for clarification!
