### ISSUE TITLE
Change animator's hierarchy no working in Unity 2019.3.4f1

### ISSUE THREAD

**Issue by caogtaa** [gydisme/Unity-Game-Framwork#5]
Thank you very much for this great tool!

I found a bug when using this tool in Unity2019.3.4f1.
Here is my animator's hierarchy. Animator is assign to node **IdiotHeroModel**. 
![image](https://user-images.githubusercontent.com/4058573/82301996-98e91d80-99eb-11ea-8688-88e150cffffa.png)

But renaming any node under **IdiotHeroModel** did not affect any animations.
After debugging, I found that Transform comparision did not work as expected, but I failed to fixed it myself.
![image](https://user-images.githubusercontent.com/4058573/82302838-b4a0f380-99ec-11ea-9238-05d03429e37b.png)

Now I just change the code to compare node name instead of Transform to workaround, but obviously it's not a robust way. 
Hope it can be fixed.
Thank you!

**Comment by gydisme** [comment]
I tested on 2019.3.13f1, it seems to work fine.
could you provide a sample project for testing?

**Comment by caogtaa** [comment]
[GolemTest.zip](https://github.com/gydisme/Unity-Game-Framwork/files/4650644/GolemTest.zip)
Thank you for your reply, please check the attackment.
Open the prefab named "MyHero", and try to rename one of its bone.
![image](https://user-images.githubusercontent.com/4058573/82330498-8257bc00-9a15-11ea-87e5-5e543c7dddf2.png)

It's good when modifiying prefab instance in Scene Hierarchy, but can't open prefab and edit in prefab hierarchy.

**Comment by gydisme** [comment]
In my test it just works fine.

![TestRename](https://user-images.githubusercontent.com/6442297/82408673-ac08f580-9a9e-11ea-8c1e-0dab7302a99f.gif)

**Comment by caogtaa** [comment]
Please try to edit in prefab hierarchy (2nd picture), not scene hierarchy (1st picture).

![image](https://user-images.githubusercontent.com/4058573/82414157-322a3980-9aa9-11ea-93bb-1f25c611ffb1.png)

![image](https://user-images.githubusercontent.com/4058573/82414502-b8df1680-9aa9-11ea-8612-cea84aef8142.png)

**Comment by caogtaa** [comment]
Because the game objects you edit is in blue color, which normally means it's an instance but not prefab itself. 
So I think you were editing in Scene Hierarchy.

**Comment by gydisme** [comment]
Okay I got your point now,
Sorry but I did't suppose to use the tool in prefab mode, because Unity is on version 5.X when I created the tool.

Please try to use the tool on an instance, the modified value will be applied to clip anyway.
Don't forget to apply prefab change after that :).

**Comment by caogtaa** [comment]
OK, it's not a big problem once we know how to workaround it.
Thank you very much.
